### Lista de contactos
GET http://localhost:3000/contactos


###Buscar en searchbar
GET http://localhost:3000/contactos/search?nombre=mej

### Crear un contacto
POST http://localhost:3000/contactos
Content-Type: application/json

{
    "primerNombre": "Eugene",
    "segundoNombre": "Kelly",
    "apellidos": "Wu Leiva",
    "telefono": "+50411332244",
    "correo": "eugene.wu@example.com"
}

### Actualizar un contacto
PATCH http://localhost:3000/contactos/6
Content-Type: application/json

{
    "primerNombre": "Gene",
    "segundoNombre": "Kelly",
    "apellidos": "Wu Leiva",
    "telefono": "+50411332244",
    "correo": "eugene.wu@example.com"
}

### Eliminar un contacto
DELETE http://localhost:3000/contactos/5

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}